from pydantic import BaseModel, Field
from typing import Annotated


class ListeningToolOutput(BaseModel):
    content: str = Field(
        ...,
        description=(
            "The text generated by the LLM containing the complete lesson content. "
            "This output should be a well-structured lesson plan that includes sections such as: "
            "Introduction, Listening Activity, Pronunciation Practice, Conversation Practice, "
            "Writing Activity, and Final Review with additional tips. It must be engaging and "
            "pedagogically sound."
        ),
        example="In this lesson, we explore effective listening strategies and practical exercises to improve English pronunciation.",
    )
    transcription: Annotated[
        str,
        Field(
            ...,
            description=(
                "The transcription of the audio or video as provided in the prompt. "
                "This field should exactly reflect the input transcription, preserving its original content for context."
            ),
            example="In this audio, the speaker discusses key aspects of English pronunciation, emphasizing rhythm and stress.",
        ),
    ]
    def to_dict(self) -> dict:
        """Converts the model to a dictionary."""
        return self.model_dump()

    def to_json(self) -> str:
        """Converts the model to a JSON string."""
        return self.model_dump_json(indent=2)
